# Github test action during pushes
name: CI Push Test
on: [push]
jobs:
  syntax:
    name: PHP Syntax Checking
    runs-on: ubuntu-latest
    #env:
    #  DB_USERNAME: root
    #  DB_PASSWORD: yii
    #  DB_CHARSET: utf8
    #services:
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
          uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
          with:
            php-version: ${{ matrix.php-versions }}
            extensions: mbstring, intl, gd, imagick, zip, dom, mysql
            coverage: xdebug #optional
      - name: PHP Version
        run: |
          php -v
      - name: List Files
        run: |
          ls -lart

